version: "3"
services:

  backend:
    build: ./backend
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=${SPRING_ACTIVE_ENVIRONMENT}
      - DB_SOURCE=${DB_SOURCE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORTD=${DB_PASSWORD}

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
