package de.uulm.automotive.cds.models

import java.util.*

/**
 * Class for the Information that the client sends on sign up.
 *
 * @property deviceType Type of the client device
 * @property signUpToken Unique token generated by the client to prevent mutliple sign ups.
 */
data class SignUpInfo(
        val deviceType: String,
        val signUpToken: UUID
)