package de.uulm.automotive.cds.entities

import java.time.LocalDateTime
import java.util.*
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.Id

@Entity
/**
 * Class that represents the SignUp Tokens.
 *
 * @property signUpToken SignUp token generated by the client.
 * @property timeLastUsed Time this token was last used.
 * @property id
 */
class SignUpToken(
    var signUpToken: UUID,
    var timeLastUsed: LocalDateTime,
    @Id @GeneratedValue var id: Long? = null
)